parameters:
#    p_turistic_test.example.class: PTuristic\TestBundle\Example

services:
#    p_turistic_test.example:
#        class: %p_turistic_test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
